* Known problems
** for short populations, the mutation ratio bugs out
   $ perl main.pl -t anna.png -p 20 -i 5000 -se output/gen2706-anna/series.014/gene_003365.txt
   Loading file 'output/gen2706-anna/series.014/gene_003365.txt'.
   22 genes loaded. The best gene has distance '0.0649357727423015' to image.
   Creating -2 mutations of the seed.
   Creating images::::::::::::::::::^C

* cleaning todos
** TODO fix order of radius strategies
** TODO rename all setters. current naming is confusing
** TODO write description for each sub
** TODO consider fixing all subs so that they take positional params
        from: 
        sub foo() {
          my $a = shift;
          my $b = shift || 0;
        }
        
        to:
        
        sub foo($a, $b=0) {
          ...
        }

** TODO prefix internal subs with underscore
* ideas
** Radius strategy
   - Start with XL radius strategy, and when it doesn't do enough, drop it and don't go back.
   - Same with L strategy - when it's not good enough, don't do that anymore
** Clean up dead alleles
   - a dead allele is one which is entirely occluded by a more recent
     circle.
   - Logically, if it was covered at some point and the distance went
     down, then it wasn't as good an allele. So it should be safe to remove.
   - However, I haven't thought it through entirely - since the BG
     image isn't homogenous, I think there's a situation where about
     half a circle matches the background.
** Diversify the population.
   - if no real change has occurred for quite some time, it's time to
     diversify the population, then let these diverse populations meet
     again.

